name: nerf
channels:
  - defaults
dependencies:
  - wheel
  - libffi
  - send2trash
  - readline
  - backcall
  - scipy
  - pickleshare
  - pexpect
  - numpy
  - jupyter
  - libxml2
  - notebook
  - jedi
  - liblapack
  - libopenblas
  - terminado
  - python_abi
  - jupyter_console
  - _openmp_mutex
  - libuuid
  - ca-certificates
  - gstreamer
  - gst-plugins-base
  - jupyterlab_pygments
  - prompt-toolkit
  - bleach
  - libgfortran5
  - certifi
  - ecos
  - libstdcxx-ng
  - openssl
  - prompt_toolkit
  - cvxpy
  - freetype
  - ncurses
  - libgcc-ng
  - pandoc
  - testpath
  - cffi
  - pip
  - qt
  - libgfortran-ng
  - libsodium
  - pcre
  - decorator
  - python
  - sip
  - scs
  - glib
  - libcblas
  - pygments
  - zeromq
  - jpeg
  - osqp
  - dbus
  - tk
  - libblas
  - ipython
  - defusedxml
  - importlib_metadata
  - zlib
  - prometheus_client
  - mistune
  - expat
  - nbclient
  - argon2-cffi
  - icu
  - traitlets
  - ld_impl_linux-64
  - entrypoints
  - fontconfig
  - ptyprocess
  - ipykernel
  - qtpy
  - pyqt
  - ipython_genutils
  - _libgcc_mutex
  - qdldl-python
  - async_generator
  - cvxpy-base
  - webencodings
  - pandocfilters
  - parso
  - xz
  - qtconsole
  - libxcb
  - pycparser
  - llvm-openmp
  - wcwidth
  - libpng
  - sqlite
  - matplotlib-inline
  - torchvision
  - pyyaml
  - cudatoolkit
  - torchaudio
