defaults:
  - _self_

wandb:
  entity: "tylerlum"
  project: "NeRF_Grasp_Metric_V1"
  name: ${datetime_str:}
  group: ""
  job_type: ""

data:
  frac_val: 0.25
  frac_test: 0.15
  frac_train: ${eval:1 - ${data.frac_val} - ${data.frac_test}}
  input_dataset_dir: "nerf_acronym_grasp_success_dataset_small_pkl"

training:
  batch_size: 512
  dataloader_num_workers: 8
  grad_clip_val: 1.0
  lr: 1e-4
  n_epochs: 20
  log_grad: True
  val_freq: 5
  val_on_epoch_0: True
  save_checkpoint_freq: 5
  save_checkpoint_on_epoch_0: False
  confusion_matrix_freq: 5
  save_confusion_matrix_on_epoch_0: True

neural_network:
  conv_channels: [16, 32]
  pool_type: "MAX"
  dropout_prob: 0.0
  conv_output_to_1d: "FLATTEN"
  mlp_hidden_layers: [256, 256, 256]

checkpoint_workspace:
  root_dir: "Train_NeRF_Grasp_Metric_workspaces"
  leaf_dir: ${wandb.name}
  force_no_resume: False

random_seed: 42

