defaults:
  - _self_

wandb:
  entity: "tylerlum"
  project: "NeRF_Grasp_Metric_V1"
  name: ${datetime_str:}
  group: ""
  job_type: ""

data:
  frac_val: 0.25
  frac_test: 0.15
  frac_train: ${eval:1 - ${data.frac_val} - ${data.frac_test}}
  input_dataset_path: "nerf_acronym_grasp_success_dataset_66_categories.h5"
  batch_size: 128
  dataloader_num_workers: 8
  dataloader_pin_memory: True

training:
  grad_clip_val: 1.0
  lr: 1e-4
  n_epochs: 20
  log_grad_freq: 5
  log_grad_on_epoch_0: False
  val_freq: 5
  val_on_epoch_0: True
  save_checkpoint_freq: 5
  save_checkpoint_on_epoch_0: False
  confusion_matrix_freq: 5
  save_confusion_matrix_on_epoch_0: False

neural_network:
  conv_channels: [32, 64, 128, 256]
  pool_type: "MAX"
  dropout_prob: 0.1
  conv_output_to_1d: "AVG_POOL_SPATIAL"
  mlp_hidden_layers: [256, 256, 256]

checkpoint_workspace:
  root_dir: "Train_NeRF_Grasp_Metric_workspaces"
  leaf_dir: ${wandb.name}
  force_no_resume: True

random_seed: 42
